### ISSUE TITLE
minimum arguments?

### ISSUE THREAD

**Issue by ghoorzehi** [brainets/netchos#1]
Thanks for sharing. 
I have a phase coherency matrix (2D) and I thought if I feed that into any of these functions, along with channel names, I may be able to get some plots out, but it seems that I was wrong.
So would any of the included plotting functions work with simply having this matrix and channel names as an input, or do I really need all other input arguments? If not, what would be the minimum number of inputs arguments one may need, to be able to plot any type of connectivity network, using this toolbox?

**Comment by EtienneCmb** [comment]
Hi @khashayar854,

Are you talking about the standard 2D heatmap? If yes, I don't think you need to provide all of the inputs. For example, here's a minimal working example : 

```python
from netchos import heatmap, circular
import numpy as np
import pandas as pd

# generate random data
n_nodes = 15
data = np.random.rand(n_nodes, n_nodes)
nodes_name = [f'roi_{k}' for k in range(n_nodes)]

# dataframe conversion
df = pd.DataFrame(data, index=nodes_name, columns=nodes_name)

# 2D heatmap
heatmap(df)

# circular plot
# circular(df)
```

**Comment by ghoorzehi** [comment]
Yeah, a simple heatmap can at least be a starting point, but I can't get that either. I copied the example code you provided above, and I get this error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/.../anaconda3/lib/python3.8/site-packages/netchos/io/io_mpl_to_px.json'

I installed the package as you had recommended by entering: pip install git+https://github.com/brainets/netchos.git and had no error when installing.

**Comment by EtienneCmb** [comment]
Ah yes, you are right I need to include this file when installing it. I'll do it asap. If you want to use now without waiting, please try :
```
git clone https://github.com/brainets/netchos.git
cd netchos
pip install -e .
```

**Comment by ghoorzehi** [comment]
Thanks. Now I get no errors but see no plots! I use Spyder and re-running the last line, heatmap(df), does not produce any plots in the plot pane, and no error in the console.

**Comment by EtienneCmb** [comment]
Yes this is because the code I sent you produces automatically the figure inside notebooks (Jupyter). Can you try with the following lines :
```python
# 2D heatmap
fig = heatmap(df)
fig.show()
```

**Comment by ghoorzehi** [comment]
Tried, still no plot.

**Comment by EtienneCmb** [comment]
Can you try :
```python
import plotly.io as pio
pio.renderers.default = 'browser'

fig = heatmap(df)
fig.show()
```

and if still doesn't works, you can try :
```python
pio.renderers.default = 'svg'
```

**Comment by ghoorzehi** [comment]
Thank you. Seem like 'browser' fixed it (sorry, python beginner here).

I can use both circular and heatmap with the example data you have above and both graphs show up perfectly.
However when I skip random data creation and create 'df' by replacing 'data' with my own adjacency matrix (2D), and 'node_name' with my list of channels (where the data type is also a list of string), and keep everything else the same, heatmap works, but circular seems to get stuck in a loop or something and never ends; the console has to be killed every time I run circle.
Any idea what might be happening?

**Comment by EtienneCmb** [comment]
Yep, you probably have a lot of links and that's why it keeps running. One workaround consist in removing some links that are not important. So for example in your case non-significant links are set to nan (not a number) or you can use a threshold. A quick example :

```
# random functional connectivity array
fc = np.random.rand(100, 100)

# use a 95th percentile threshold
th = np.percentile(fc, 95)

# set to nan every non-significant links
fc[fc < th] = np.nan

# dataframe conversion + circular plot
....
```

**Comment by ghoorzehi** [comment]
Yes, that was the problem.
Thanks so much for your help and clear examples. Once I fully compute my connectivity data and organise them, would love to come back to this package and try to visualise them, perhaps using more detailed arguments...
But for now this would do the job.
Thanks again.
