### ISSUE TITLE
"zero-size array" error with circular plot

### ISSUE THREAD

**Issue by ghoorzehi** [brainets/netchos#3]
the circular plot gives the following error:
"ValueError: zero-size array to reduction operation fmin which has no identity"

same data works fine with heatmap()
Data that is passed on is the result of the connectivity matrix from MNE (where only the bottom triangle of the connectivity matrix is computed and upper triangle is zero) as follows:
'coh' as connectivity method, averaged over selected frequency, so a 64 by 64 connectivity matrix. 95th percentile is taken to reduce the number of connections.

**Comment by EtienneCmb** [comment]
Hi @khashayar854,

Can you show me the code please? You might need to transform it to a pandas dataframe. Something like this :

```python
df = pd.DataFrame(coh, index=ch_names, columns=ch_names)
circular(df)
```

**Comment by ghoorzehi** [comment]
Yes I had. Circular used to work with my own connectivity function. But it seems that it doesn't like MNE connectivity for some reason? 

```
th = np.percentile(am, 95)
# set to nan every non-significant links
am[am < th] = np.nan
df = pd.DataFrame(am, index=chans, columns=chans) # am is the adjecency matrix, chans is the list of channels

fig = circular(df)
fig.show()
```

**Comment by EtienneCmb** [comment]
Maybe netchos has a different convention in the orientation of the upper / lower triangle. Could you try the two following tests:

```python
# number of significant links
print(np.sum(~np.isnan(am)))

# try to transpose the array
df = pd.DataFrame(am.T, index=chans, columns=chans)
```

**Comment by ghoorzehi** [comment]
Yes, thank you. 
The orientation of the upper/lower triangle was indeed the issue, and transposing the adjacency matrix solved it.
Of course, heatmap() didn't have any issue with the orientation of the triangle since it could accept either, not circular() though.
maybe checking the orientation of the triangle can be added to the circular function so that it transposes df automatically if needed, so it would directly work with MNE with no extra step too? 
Thanks for the tip.

**Comment by EtienneCmb** [comment]
Yes, indeed, netchos should perform this test. I didn't thought about this before. If I remember correctly, I think `scipy` has functions to check if symmetrical arrays are corrects. Could you check it?

**Comment by khashayar854** [comment]
Sorry, python beginner here. Not sure if there is a built-in function for
it, but it seems like people have some suggestions here:
https://stackoverflow.com/questions/42908334/checking-if-a-matrix-is-symmetric-in-numpy

**Comment by ghoorzehi** [comment]
Sorry, python beginner here. Not sure if there is a built-in function for it, but it seems like people have some suggestions here:
https://stackoverflow.com/questions/42908334/checking-if-a-matrix-is-symmetric-in-numpy
